print('hello', 'world','from Romania',sep='###', end='%')
print('hello', 'world','from Romania')
print('hello', 'world','from Romania')


print('****************')
print('*              *')
print('*              *')
print('*              *')
print('*              *')
print('*              *')
print('****************')

print(         ' * '   )
print(        ' * *' )
print(      ' *    *'  )
print(     ' *      * '  )
print(   ' *         *  ' )
print(  '*            * ' )
print('****************'  )